# Common package bundle

{ lib, baremetal, ... }:

[
  "-dnsmasq"
  "dnsmasq-full"
  "-ethtool"
  "ethtool-full"
  "vim"
  "vim-runtime"

  "ip-full"
  "iptables-nft"
  "ip6tables-nft"

  "kmod-nf-nat"
  "kmod-nf-nat6"
  "kmod-nf-nathelper"
  "kmod-nf-nathelper-extra"
  "kmod-nfnetlink"
  "kmod-nfnetlink-log"
  "kmod-nfnetlink-queue"
  "kmod-nlmon"
  "kmod-nft-arp"
  "kmod-nft-bridge"
  "kmod-nft-compat"
  "kmod-nft-connlimit"
  "kmod-nft-dup-inet"
  "kmod-nft-netdev"
  "kmod-nft-queue"
  "kmod-nft-socket"
  "kmod-nft-tproxy"
  "kmod-nft-xfrm"
  "kmod-nft-offload"
  "kmod-ipt-tproxy"
  "kmod-ipt-nat6"
  "kmod-ipt-nat-extra"
  "kmod-ipt-offload"
  "kmod-tls"
  "kmod-sched-mqprio"
  "kmod-tcp-bbr"

  "htop"
  "minicom"
  "postfix"
  "ca-bundle"
  "bind-host"
  "bind-dig"
  "httping"
  "tcping"
  "wget-ssl"
  "iperf3"
  "telnet-bsd"
  "speedtest-cli"
  "lscpu"
  "lsblk"

  "luci-i18n-base-zh-cn"
  "luci-i18n-opkg-zh-cn"
  "luci-i18n-firewall-zh-cn"
  "luci-proto-wireguard"
] ++ (lib.optionals baremetal [
  "intel-microcode"
  "iucode-tool"
  "kmod-kvm-intel"
  "kmod-i2c-i801"
  "kmod-itco-wdt"

  "lm-sensors-detect"
  "lm-sensors"
  "losetup"
]) ++ (lib.optionals (!baremetal) [
  "qemu-ga"
  "virtio-console-helper"
])
